### ISSUE TITLE
Can't build on a fresh project download

### ISSUE THREAD

**Issue by t-lock** [simolus3/zap#20]
Hello!

I am extremely interested in this project, but I can't get a build running.

I downloaded the starter bundle, unzipped, checked readme, and both the dev and build commands failed straightaway.

Any ideas?

Log output:

```
❯ dart run webdev build
[INFO] ../../../.pub-cache/hosted/pub.dev/build_modules-4.0.5/lib/src/module_cache.dart:21:70: Error:
[INFO] Try correcting the name to the name of an existing method, or defining a method named 'toJson'
[INFO] ../../../.pub-cache/hosted/pub.dev/build_modules-4.0.5/lib/src/module_cache.dart:24:66: Error:
[INFO] Try correcting the name to the name of an existing method, or defining a method named 'toJson'
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
[SEVERE] This is likely caused by a misconfigured builder definition.
[SEVERE] 
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup.<anonymous closure> (package:build_daemon/client.dart:79:21)
#1      _runUserCode (dart:async/stream_pipe.dart:11:23)
#2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1704:9)
#3      _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:399:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:398:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:268:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:505:27)
#12     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#16     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#17     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#18     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#19     _LineSplitterSink.close (dart:convert/line_splitter.dart:137:11)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#25     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#26     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#27     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#28     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#29     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
#30     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#31     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#32     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#33     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#34     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#35     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
#36     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
#37     _StreamController.close (dart:async/stream_controller.dart:630:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:2362:21)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#43     _StreamController._add (dart:async/stream_controller.dart:648:7)
#44     _StreamController.add (dart:async/stream_controller.dart:596:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1884:35)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1327:18)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

**Comment by t-lock** [comment]
And output of `dart run webdev serve --auto refresh`:

```
Building package executable... (3.1s)
Built webdev:webdev.
[INFO] ../../../.pub-cache/hosted/pub.dev/build_modules-4.0.5/lib/src/module_cache.dart:21:70: Error:
[INFO] Try correcting the name to the name of an existing method, or defining a method named 'toJson'
[INFO] ../../../.pub-cache/hosted/pub.dev/build_modules-4.0.5/lib/src/module_cache.dart:24:66: Error:
[INFO] Try correcting the name to the name of an existing method, or defining a method named 'toJson'
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
[SEVERE] This is likely caused by a misconfigured builder definition.
[SEVERE] 
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup.<anonymous closure> (package:build_daemon/client.dart:79:21)
#1      _runUserCode (dart:async/stream_pipe.dart:11:23)
#2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1704:9)
#3      _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:399:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:398:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:268:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:505:27)
#12     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#16     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#17     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#18     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#19     _LineSplitterSink.close (dart:convert/line_splitter.dart:137:11)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#25     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#26     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#27     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#28     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#29     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
#30     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#31     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#32     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#33     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#34     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#35     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
#36     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
#37     _StreamController.close (dart:async/stream_controller.dart:630:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:2362:21)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#43     _StreamController._add (dart:async/stream_controller.dart:648:7)
#44     _StreamController.add (dart:async/stream_controller.dart:596:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1884:35)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1327:18)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

**Comment by t-lock** [comment]
And `dart analyze` as well:

```
❯ dart analyze
Analyzing zap_test...                  0.4s

  error • web/main.dart:4:8 • Target of URI doesn't exist: 'package:zap_test/app.zap.dart'. Try creating the file referenced by the URI,
          or try using a URI for a file that does exist. • uri_does_not_exist
  error • web/main.dart:7:3 • The function 'App' isn't defined. Try importing the library that defines 'App', correcting the name to the
          name of an existing function, or defining a function named 'App'. • undefined_function
warning • analysis_options.yaml:1:10 • The include file 'package:lints/analysis_options.yaml' in
          '/home/tlock/Sites/TLock/zap_test/analysis_options.yaml' can't be found when analyzing '/home/tlock/Sites/TLock/zap_test'. •
          include_file_not_found

3 issues found.
```

**Comment by simolus3** [comment]
Thanks for your interest! I've updated the packages and the example, it should work now.

**Comment by t-lock** [comment]
@simolus3 Thanks!

Made it a bit further this time, but now I'm getting:

```
[SEVERE] build_web_compilers:entrypoint on web/main.dart (cached): Bad state: Unable to locate required sdk resource build_web_compilers|lib/src/dev_compiler/dart_sdk.sound.js

[SEVERE] build_web_compilers:sdk_js on asset:build_web_compilers/$package$ (cached): Error compiling dartdevc module:build_web_compilers|lib/src/dev_compiler/dart_sdk.sound.js
```

I  installed Dart and the Flutter SDK quite a while ago (and just updated). I'm not using Flutter at the moment so I may just try uninstalling my whole Dart toolchain and reinstalling (without Flutter).

Unless you think that this is an issue on the zap project side?

Apologies, a bit new to Dart and its tooling.

**Comment by simolus3** [comment]
No worries! Can you check that you're on Dart 3.x and using version 4.x of the `build_web_compilers` package?
